site_name: UI/UX Writing Guide
theme:
  name: material

nav:
  - Home: index.md
  - UX_writing: ux-writing.md
  - UX/UI best practices: ux-ui-writing-doc.md
  - UI/UXvsFigma: UX_UI_checklist.md
  - UI/UXExample: UX_UI_example.md

extra:
  generator: falsels